### ISSUE TITLE
Your licenses are in conflict

### ISSUE THREAD

**Issue by yyyc514** [highlightjs/highlightjs-shexc#5]
Your LICENSE file is MIT but your README says CC0.

**Comment by ericprud** [comment]
good point. I don't care which. What do you recommend will make it easiest for folks to use/extend/steal ?

**Comment by yyyc514** [comment]
No idea. :)   I usually do MIT because Ruby on Rails is, but I really have no legal advice to offer. :-)

**Comment by yyyc514** [comment]
Also http://www.wtfpl.net LOL.

**Comment by ericprud** [comment]
Ha! I like the idea of wtfpl a lot, but I found an badge for MIT so went with that.

**Comment by yyyc514** [comment]
https://badgen.net

Don't let badge dictate your license, easy enough to make a badge for anything.

<img src=https://badgen.net/badge/license/WTFPL/blue>
